<?php
/**
 * Name: FOCUS Object Cache
 * Plugin URI: http://wordpress.org/plugins/focus-object-cache/
 * Description: File-based Object Cache is Utterly Slow: An Object Caching Dropin for WordPress that uses the local file system.
 * Version: 1.0.2
 * Text Domain: focus-cache
 * Author: Derrick Tennant
 * Author URI: https://emrikol.com/
 * GitHub Plugin URI: https://github.com/emrikol/focus/
 * License: GPLv3
 * License URI: http://www.gnu.org/licenses/gpl-3.0.html
 *
 * @package WordPress
 */

declare(strict_types=1);

// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedFunctionFound, WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedConstantFound, WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedClassFound

/**
 * Users with setups where multiple installs share a common wp-config.php or
 * $table_prefix can use this to guarantee uniqueness for the keys generated by
 * this object cache
 */
if ( ! defined( 'WP_CACHE_KEY_SALT' ) ) {
	define( 'WP_CACHE_KEY_SALT', '' );
}

/**
 * Defines the max expiry age for FOCUS objects.
 */
if ( ! defined( 'WP_FOCUS_MAXTTL' ) ) {
	// Use YEAR_IN_SECONDS if available, otherwise default to one year.
	if ( defined( 'YEAR_IN_SECONDS' ) ) {
		define( 'WP_FOCUS_MAXTTL', YEAR_IN_SECONDS );
	} else {
		define( 'WP_FOCUS_MAXTTL', 365 * 24 * 60 * 60 );
	}
}

/**
 * Enables cache preloading functionality for performance optimization.
 * When enabled, the entire cache state is saved at the end of each request
 * and restored at the beginning of subsequent requests for the same URL.
 */
if ( ! defined( 'WP_FOCUS_CACHE_PRELOAD' ) ) {
	define( 'WP_FOCUS_CACHE_PRELOAD', false );
}

/**
 * Defines the TTL (time-to-live) for cache preload files in seconds.
 * Preload files older than this will be considered expired and ignored.
 */
if ( ! defined( 'WP_FOCUS_PRELOAD_TTL' ) ) {
	define( 'WP_FOCUS_PRELOAD_TTL', 300 ); // 5 minutes
}

/**
 * From WordPress Core: Adds data to the cache, if the cache key doesn't already exist.
 *
 * @param int|string $key    The cache key to use for retrieval later.
 * @param mixed      $data   The data to add to the cache.
 * @param string     $group  Optional. The group to add the cache to. Enables the same key
 *                           to be used across groups. Default empty.
 * @param int        $expire Optional. When the cache data should expire, in seconds.
 *                           Default 0 (no expiration).
 * @return bool False if cache key and group already exist, true on success.
 */
function wp_cache_add( int|string $key, mixed $data, string $group = 'default', int $expire = 0 ): bool {
	global $wp_object_cache;

	// Skip persistent cache operations during WordPress installation.
	if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
		( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		return true;
	}

	return $wp_object_cache->add( $key, $data, $group, $expire );
}

/**
 * From WordPress Core: Adds a group or set of groups to the list of global groups.
 *
 * @param string|array $groups A group or an array of groups to add.
 *
 * @return void
 */
function wp_cache_add_global_groups( string|array $groups ): void {
	global $wp_object_cache;
	$wp_object_cache->add_global_groups( $groups );
}

/**
 * From WordPress Core: Closes the cache.
 *
 * This function has ceased to do anything since WordPress 2.5. The
 * functionality was removed along with the rest of the persistent cache.
 *
 * This does not mean that plugins can't implement this function when they need
 * to make sure that the cache is cleaned up after WordPress no longer needs it.
 *
 * @return bool Always returns true.
 */
function wp_cache_close(): bool {
	return true;
}

/**
 * From WordPress Core: Decrements numeric cache item's value.
 *
 * @param int|string $key    The cache key to decrement.
 * @param int        $offset Optional. The amount by which to decrement the item's value. Default 1.
 * @param string     $group  Optional. The group the key is in. Default empty.
 *
 * @return false|int False on failure, the item's new value on success.
 */
function wp_cache_decr( int|string $key, int $offset = 1, string $group = 'default' ): false|int {
	global $wp_object_cache;

	// Skip persistent cache operations during WordPress installation.
	if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
		( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		return false;
	}

	return $wp_object_cache->decr( $key, $offset, $group );
}

/**
 * From WordPress Core: Removes the cache contents matching key and group.
 *
 * @param int|string $key   What the contents in the cache are called.
 * @param string     $group Optional. Where the cache contents are grouped. Default empty.
 *
 * @return bool True on successful removal, false on failure.
 */
function wp_cache_delete( int|string $key, string $group = 'default' ): bool {
	global $wp_object_cache;

	// Skip persistent cache operations during WordPress installation.
	if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
		( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		return true;
	}

	return $wp_object_cache->delete( $key, $group );
}

/**
 * Removes cache contents for a given group.
 *
 * @param string $group Where the cache contents are grouped.
 *
 * @return bool True on successful removal, false on failure
 */
function wp_cache_delete_group( string $group ): bool {
	global $wp_object_cache;
	return $wp_object_cache->delete_group( $group );
}

/**
 * From WordPress Core: Removes all cache items.
 *
 * @return bool False on failure, true on success
 */
function wp_cache_flush(): bool {
	global $wp_object_cache;
	return $wp_object_cache->flush();
}

/**
 * Flush the object cache's runtime cache.
 *
 * @return bool True on success, false on failure.
 */
function wp_cache_flush_runtime(): bool {
	global $wp_object_cache;
	return $wp_object_cache->flush_runtime();
}

/**
 * From WordPress Core: Retrieves the cache contents from the cache by key and group.
 *
 * @param int|string $key What the contents in the cache are called.
 * @param string     $group Where the cache contents are grouped.
 * @param bool       $force Whether to force an update of the local cache from the persistent cache (default is false).
 * @param bool       $found Whether key was found in the cache. Disambiguates a return of false, a storable value.
 *
 * @return mixed False on failure to retrieve contents or the cache contents on success
 */
function wp_cache_get( int|string $key, string $group = 'default', bool $force = false, bool &$found = null ): mixed {
	global $wp_object_cache;

	// Skip persistent cache operations during WordPress installation.
	if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
		( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		$found = false;
		return false;
	}

	return $wp_object_cache->get( $key, $group, $force, $found );
}

/**
 * From WordPress Core: Increment numeric cache item's value
 *
 * @param int|string $key    The key for the cache contents that should be incremented.
 * @param int        $offset Optional. The amount by which to increment the item's value. Default 1.
 * @param string     $group  Optional. The group the key is in. Default empty.
 *
 * @return false|int False on failure, the item's new value on success.
 */
function wp_cache_incr( int|string $key, int $offset = 1, string $group = 'default' ): false|int {
	global $wp_object_cache;

	// Skip persistent cache operations during WordPress installation.
	if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
		( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		return false;
	}

	return $wp_object_cache->incr( $key, $offset, $group );
}

/**
 * From WordPress Core: Sets up Object Cache Global and assigns it.
 *
 * @return void
 */
function wp_cache_init(): void {
	global $wp_object_cache;
	$wp_object_cache = new WP_Object_Cache(); // phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited
}

/**
 * From WordPress Core: Replaces the contents of the cache with new data.
 *
 * @param int|string $key    The key for the cache data that should be replaced.
 * @param mixed      $data   The new data to store in the cache.
 * @param string     $group  Optional. The group for the cache data that should be replaced.
 *                           Default empty.
 * @param int        $expire Optional. When to expire the cache contents, in seconds.
 *                           Default 0 (no expiration).
 *
 * @return bool False if original value does not exist, true if contents were replaced
 */
function wp_cache_replace( int|string $key, mixed $data, string $group = 'default', int $expire = 0 ): bool {
	global $wp_object_cache;

	// Skip persistent cache operations during WordPress installation.
	if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
		( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		return true;
	}

	return $wp_object_cache->replace( $key, $data, $group, $expire );
}

/**
 * From WordPress Core: Saves the data to the cache.
 *
 * Differs from wp_cache_add() and wp_cache_replace() in that it will always write data.
 *
 * @param int|string $key    The cache key to use for retrieval later.
 * @param mixed      $data   The contents to store in the cache.
 * @param string     $group  Optional. Where to group the cache contents. Enables the same key
 *                           to be used across groups. Default empty.
 * @param int        $expire Optional. When to expire the cache contents, in seconds.
 *                           Default 0 (no expiration).
 *
 * @return bool False on failure, true on success
 */
function wp_cache_set( int|string $key, mixed $data, string $group = 'default', int $expire = 0 ): bool {
	global $wp_object_cache;

	// Skip persistent cache operations during WordPress installation.
	if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
		( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		return true;
	}

	return $wp_object_cache->set( $key, $data, $group, $expire );
}

/**
 * From WordPress Core: Switches the interal blog ID.
 *
 * This changes the blog id used to create keys in blog specific groups.
 *
 * @param int $blog_id Site ID.
 *
 * @return void
 */
function wp_cache_switch_to_blog( int $blog_id ): void {
	global $wp_object_cache;
	$wp_object_cache->switch_to_blog( $blog_id );
}

/**
 * From WordPress Core: Adds a group or set of groups to the list of non-persistent groups.
 *
 * @param string|array $groups A group or an array of groups to add.
 *
 * @return void
 */
function wp_cache_add_non_persistent_groups( string|array $groups ): void {
	global $wp_object_cache;
	$wp_object_cache->add_non_persistent_groups( $groups );
}

/**
 * Adds multiple values to the cache in one call.
 *
 * @param array  $data   Array of keys and values to be set.
 * @param string $group  Optional. Where the cache contents are grouped. Default empty.
 * @param int    $expire Optional. When to expire the cache contents, in seconds.
 *                       Default 0 (no expiration).
 *
 * @return bool[] Array of return values, grouped by key. Each value is either
 *                true on success, or false if cache key and group already exist.
 */
function wp_cache_add_multiple( array $data, string $group = '', int $expire = 0 ): array {
	global $wp_object_cache;

	// Skip persistent cache operations during WordPress installation.
	if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
		( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		return array_fill_keys( array_keys( $data ), true );
	}

	return $wp_object_cache->add_multiple( $data, $group, $expire );
}

/**
 * Sets multiple values to the cache in one call.
 *
 * @param array  $data   Array of keys and values to be set.
 * @param string $group  Optional. Where the cache contents are grouped. Default empty.
 * @param int    $expire Optional. When to expire the cache contents, in seconds.
 *                       Default 0 (no expiration).
 *
 * @return bool[] Array of return values, grouped by key. Each value is either
 *                true on success, or false on failure.
 */
function wp_cache_set_multiple( array $data, string $group = '', int $expire = 0 ): array {
	global $wp_object_cache;

	// Skip persistent cache operations during WordPress installation.
	if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
		( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		return array_fill_keys( array_keys( $data ), true );
	}

	return $wp_object_cache->set_multiple( $data, $group, $expire );
}

/**
 * Retrieves multiple values from the cache in one call.
 *
 * @param array  $keys  Array of keys under which the cache contents are stored.
 * @param string $group Optional. Where the cache contents are grouped. Default empty.
 * @param bool   $force Optional. Whether to force an update of the local cache
 *                      from the persistent cache. Default false.
 *
 * @return array Array of return values, grouped by key. Each value is either
 *               the cache contents on success, or false on failure.
 */
function wp_cache_get_multiple( array $keys, string $group = '', bool $force = false ): array {
	global $wp_object_cache;

	// Skip persistent cache operations during WordPress installation.
	if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
		( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		return array_fill_keys( $keys, false );
	}

	return $wp_object_cache->get_multiple( $keys, $group, $force );
}

/**
 * Deletes multiple values from the cache in one call.
 *
 * @param array  $keys  Array of keys under which the cache to deleted.
 * @param string $group Optional. Where the cache contents are grouped. Default empty.
 *
 * @return bool[] Array of return values, grouped by key. Each value is either
 *                true on success, or false if the contents were not deleted.
 */
function wp_cache_delete_multiple( array $keys, string $group = '' ): array {
	global $wp_object_cache;

	// Skip persistent cache operations during WordPress installation.
	if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
		( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		return array_fill_keys( $keys, true );
	}

	return $wp_object_cache->delete_multiple( $keys, $group );
}

/**
 * Removes all cache items in a group, if the object cache implementation supports it.
 *
 * Before calling this function, always check for group flushing support using the
 * `wp_cache_supports( 'flush_group' )` function.
 *
 * @param string $group Name of group to remove from cache.
 *
 * @return bool True if group was flushed, false otherwise.
 */
function wp_cache_flush_group( string $group ): bool {
	global $wp_object_cache;

	// Skip persistent cache operations during WordPress installation.
	if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
		( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
		return true;
	}

	/**
	 * WordPress core expects external object caches to trigger a "doing it wrong" notice
	 * and return false unless they explicitly support group flushing through wp_cache_supports().
	 * This maintains compatibility with WordPress core tests and expectations.
	 * See: WordPress core test Tests_Cache::test_wp_cache_flush_group()
	 */
	if ( wp_using_ext_object_cache() ) {
		if ( ! wp_cache_supports( 'flush_group' ) ) {
			_doing_it_wrong(
				__FUNCTION__,
				esc_html__( 'wp_cache_flush_group() is not supported by the current object cache backend.', 'focus-cache' ),
				'6.1.0'
			);
			return false;
		}
	}

	// Cache supports group flushing - proceed with the operation.
	if ( method_exists( $wp_object_cache, 'flush_group' ) ) {
		return $wp_object_cache->flush_group( $group );
	}

	// Fallback - should not reach here if wp_cache_supports is implemented correctly.
	return false;
}

/**
 * Determines whether the object cache implementation supports a particular feature.
 *
 * @param string $feature Name of the feature to check for. Possible values include:
 *                        'add_multiple', 'set_multiple', 'get_multiple', 'delete_multiple',
 *                        'flush_runtime', 'flush_group'.
 *
 * @return bool True if the feature is supported, false otherwise.
 */
function wp_cache_supports( string $feature ): bool {
	switch ( $feature ) {
		case 'add_multiple':
		case 'set_multiple':
		case 'get_multiple':
		case 'delete_multiple':
		case 'flush_runtime':
		case 'flush_group':
			return true;

		default:
			return false;
	}
}
// phpcs:enable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedFunctionFound, WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedConstantFound

/**
 * From WordPress Core: Core class that implements an object cache.
 *
 * The WordPress Object Cache is used to save on trips to the database. The
 * Object Cache stores all of the cache data to memory and makes the cache
 * contents available by using a key, which is used to name and later retrieve
 * the cache contents.
 *
 * This implementation of the object cache uses flat files to store objects
 * and overrides the core non-persistent cache.
 */
class WP_Object_Cache {
	/**
	 * The amount of times the cache data was already stored in the cache.
	 *
	 * @since 0.1.0
	 * @access public
	 * @var int
	 */
	public $cache_hits = 0;

	/**
	 * Amount of times the cache did not have the request in cache.
	 *
	 * @since 0.1.0
	 * @access public
	 * @var int
	 */
	public $cache_misses = 0;

	/**
	 * Stores operations by group for stats
	 *
	 * @since 0.1.0
	 * @access private
	 * @var int
	 */
	public array $group_ops = array();

	/**
	 * Holds the cached objects.
	 *
	 * @since 0.1.0
	 * @access private
	 * @var array
	 */
	public array $cache = array();

	/**
	 * List of global cache groups.
	 *
	 * @since 0.1.0
	 * @access protected
	 * @var array
	 */
	public array $global_groups = array();

	/**
	 * Groups that should not be stored in persistent cache.
	 *
	 * @since 0.1.0
	 * @access private
	 * @var array
	 */
	public array $non_persistent_groups = array( 'comment' => true );

	/**
	 * The blog prefix to prepend to keys in non-global groups.
	 *
	 * @since 0.1.0
	 * @access private
	 * @var int
	 */
	public string $blog_prefix;

	/**
	 * The global prefix to prepend to keys in global groups.
	 *
	 * @since 0.2.0
	 * @access private
	 * @var string
	 */
	public string $global_prefix;

	/**
	 * Cache key salt for uniqueness.
	 *
	 * @since 0.2.0
	 * @access private
	 * @var string
	 */
	public string $key_salt;

	/**
	 * Directory where cache files are stored.
	 *
	 * @since 0.1.0
	 * @access private
	 * @var string
	 */
	public string $cache_dir;

	/**
	 * Directory for cache preload files.
	 *
	 * @since 1.1.0
	 * @access private
	 * @var string
	 */
	public string $preload_dir;

	/**
	 * Test mode flag for preload functionality.
	 *
	 * @since 1.1.0
	 * @access private
	 * @var bool
	 */
	public bool $test_preload_enabled = false;

	/**
	 * Used to detect if script is running via WP-CLI.
	 *
	 * @since 1.1.0
	 * @access private
	 * @var bool
	 */
	public ?bool $is_wp_cli = null;

	/**
	 * Used to detect if script is running via WordPress cron.
	 *
	 * @since 1.1.0
	 * @access private
	 * @var bool
	 */
	public ?bool $is_doing_cron = null;

	/**
	 * Used to detect if script is running via XML-RPC.
	 *
	 * @since 1.1.0
	 * @access private
	 * @var bool
	 */
	public ?bool $is_xmlrpc_request = null;

	/**
	 * Secret to use for a hash salt.
	 *
	 * @since 0.1.0
	 * @access private
	 * @var string
	 */
	public string $secret = '';

	/**
	 * Default maximum cache expiry.
	 *
	 * @since 0.1.0
	 * @access private
	 * @var int
	 */
	public $default_expiration = WP_FOCUS_MAXTTL;

	/**
	 * Cache file header.
	 *
	 * @since 0.1.0
	 * @access private
	 * @var string
	 */
	public string $cache_serial_header = '<?php return; /*';

	/**
	 * Cache file footer.
	 *
	 * @since 0.1.0
	 * @access private
	 * @var string
	 */
	public string $cache_serial_footer = '*/ ?>';

	/**
	 * File path cache to avoid repeated calculations.
	 *
	 * @since 1.0.0
	 * @access private
	 * @var array
	 */
	public array $file_path_cache = array();

	/**
	 * Expiration cache to avoid repeated filemtime() calls.
	 *
	 * @since 1.0.0
	 * @access private
	 * @var array
	 */
	public array $expiration_cache = array();

	/**
	 * Maximum number of items to keep in file path cache before cleanup.
	 *
	 * @since 1.0.0
	 * @access private
	 * @var int
	 */
	public int $max_file_path_cache_items = 1000;

	/**
	 * Number of items to keep when cleaning up file path cache.
	 *
	 * @since 1.0.0
	 * @access private
	 * @var int
	 */
	public int $file_path_cache_cleanup_size = 500;

	/**
	 * Maximum number of items to keep in expiration cache before cleanup.
	 *
	 * @since 1.0.0
	 * @access private
	 * @var int
	 */
	public int $max_expiration_cache_items = 1000;

	/**
	 * Number of items to keep when cleaning up expiration cache.
	 *
	 * @since 1.0.0
	 * @access private
	 * @var int
	 */
	public int $expiration_cache_cleanup_size = 500;

	/**
	 * Minimum free disk space required before writing cache files (in bytes).
	 *
	 * @since 1.0.0
	 * @access private
	 * @var int
	 */
	public int $min_disk_space = 10485760; // 10MB.

	/**
	 * Sets up object properties.
	 *
	 * @since 0.1.0
	 *
	 * @global int $blog_id Global blog ID.
	 */
	public function __construct() {
		global $blog_id;

		// Ensure blog_id is set, default to 1 if not available yet.
		if ( ! isset( $blog_id ) || empty( $blog_id ) ) {
			$blog_id = 1; // phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited
		}

		if ( defined( 'CACHE_PATH' ) ) {
			$this->cache_dir = CACHE_PATH;
		} else {
			// Ensure WP_CONTENT_DIR is defined.
			if ( ! defined( 'WP_CONTENT_DIR' ) ) {
				if ( defined( 'ABSPATH' ) ) {
					define( 'WP_CONTENT_DIR', ABSPATH . 'wp-content' );
				} else {
					// Fallback for test environment.
					define( 'WP_CONTENT_DIR', '/tmp/wordpress/wp-content' );
				}
			}
			$this->cache_dir = WP_CONTENT_DIR . DIRECTORY_SEPARATOR . 'focus-object-cache' . DIRECTORY_SEPARATOR;
		}

		// Set up preload directory.
		$this->preload_dir = $this->cache_dir . 'preload' . DIRECTORY_SEPARATOR;

		// Skip cache directory creation during WordPress installation.
		if ( ! ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
				( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.MissingUnslash, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
			$this->mkdir( $this->cache_dir );

			// Create preload directory if preload is enabled.
			if ( WP_FOCUS_CACHE_PRELOAD ) {
				$this->mkdir( $this->preload_dir );
			}
		}

		$this->salt_keys( WP_CACHE_KEY_SALT );
		$this->global_prefix = 'Global';
		$this->blog_prefix   = 'WP';

		if ( function_exists( 'is_multisite' ) && is_multisite() ) {
			$this->blog_prefix = 'Site ' . $blog_id;
		}

		// Load preload cache if enabled and available.
		if ( WP_FOCUS_CACHE_PRELOAD || ( isset( $this->test_preload_enabled ) && $this->test_preload_enabled ) ) {
			$this->load_preload_cache();

			// Register shutdown hook to save preload cache.
			register_shutdown_function( array( $this, 'save_preload_cache' ) );
		}
	}

	/**
	 * Saves the object cache before object is completely destroyed.
	 *
	 * Called upon object destruction, which should be when PHP ends.
	 *
	 * @since 0.1.8
	 *
	 * @return void
	 */
	public function __destruct() {
		// Destructor method - no action needed.
	}

	/**
	 * Adds data to the cache if it doesn't already exist.
	 *
	 * @since 0.1.0
	 * @access public
	 *
	 * @uses WP_Object_Cache::isset_internal() Checks to see if the cache already has data.
	 * @uses WP_Object_Cache::set()             Sets the data after the checking the cache contents existence.
	 *
	 * @param int|string $key    What to call the contents in the cache.
	 * @param mixed      $data   The contents to store in the cache.
	 * @param string     $group  Optional. Where to group the cache contents. Default 'default'.
	 * @param int        $expire Optional. When to expire the cache contents. Default 0 (maximum expiration).
	 * @return bool False if cache key and group already exist, true on success
	 */
	public function add( int|string $key, mixed $data, string $group = 'default', int $expire = 0 ): bool {
		// Skip persistent cache operations during WordPress installation.
		if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
			( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
			return true;
		}

		if ( wp_suspend_cache_addition() ) {
			return false;
		}

		if ( ! $this->is_valid_key( $key ) ) {
			return false;
		}

		$group = $this->sanitize_cache_group( $group );
		$key   = $this->key( $key, $group );

		if ( $this->isset_internal( $key, $group ) ) {
			return false;
		}

		$force = null;
		if ( false !== $this->get( $key, $group, false, $force, false ) ) {
			return false;
		}

		return $this->set( $key, $data, $group, (int) $expire );
	}

	/**
	 * Sets the list of global cache groups.
	 *
	 * @since 0.1.0
	 * @access public
	 *
	 * @param array|string $groups List of groups that are global.
	 */
	public function add_global_groups( array|string $groups ): void {
		$groups = (array) $groups;

		// Add and dedupe groups.
		$groups              = array_fill_keys( $groups, true );
		$this->global_groups = array_merge( $this->global_groups, $groups );
		$this->global_groups = array_unique( $this->global_groups );
	}

	/**
	 * Sets the list of non-persistent cache groups.
	 *
	 * @since 0.1.0
	 * @access public
	 *
	 * @param array|string $groups List of groups that are global.
	 */
	public function add_non_persistent_groups( array|string $groups ): void {
		$groups = (array) $groups;

		// Add and dedupe groups.
		$groups                      = array_fill_keys( $groups, true );
		$this->non_persistent_groups = array_merge( $this->non_persistent_groups, $groups );
		// No need for array_unique since array_merge already handles duplicates for associative arrays.
	}

	/**
	 * Decrements numeric cache item's value.
	 *
	 * @since 0.1.0
	 * @access public
	 *
	 * @param int|string $key    The cache key to decrement.
	 * @param int        $offset Optional. The amount by which to decrement the item's value. Default 1.
	 * @param string     $group  Optional. The group the key is in. Default 'default'.
	 * @return false|int False on failure, the item's new value on success.
	 */
	public function decr( int|string $key, int $offset = 1, string $group = 'default' ): int|false {
		if ( ! $this->is_valid_key( $key ) ) {
			return false;
		}

		$group = $this->sanitize_cache_group( $group );
		$key   = $this->key( $key, $group );

		// Key/Group doesn't exist, return false.
		if ( ! $this->isset_internal( $key, $group ) ) {
			return false;
		}

		// Get current expiration BEFORE modifying the value to avoid race conditions.
		$current_expiry = $this->get_expiration( $key, $group );
		if ( $current_expiry < 0 ) {
			// Value has expired, delete it and return false.
			$this->delete( $key, $group );
			return false;
		}

		// Sanitize value.
		$this->cache[ $group ][ $key ] = (int) $this->cache[ $group ][ $key ];

		// Sanitize offset.
		$offset = (int) $offset;

		// Decrement value.
		$this->cache[ $group ][ $key ] -= $offset;

		// Do not let value go negative.
		$this->cache[ $group ][ $key ] = max( 0, $this->cache[ $group ][ $key ] );

		// Save new value to the cache with preserved expiration.
		$this->set( $key, $this->cache[ $group ][ $key ], $group, $current_expiry );

		// Return new value.
		return $this->cache[ $group ][ $key ];
	}

	/**
	 * Removes the contents of the cache key in the group.
	 *
	 * If the cache key does not exist in the group, then nothing will happen.
	 *
	 * @since 0.1.0
	 * @access public
	 *
	 * @param int|string $key        What the contents in the cache are called.
	 * @param string     $group      Optional. Where the cache contents are grouped. Default 'default'.
	 * @return bool False if the contents weren't deleted and true on success.
	 */
	public function delete( int|string $key, string $group = 'default' ): bool {
		if ( ! $this->is_valid_key( $key ) ) {
			return false;
		}

		$group  = $this->sanitize_cache_group( $group );
		$key    = $this->key( $key, $group );
		$return = true;

		// Key/Group doesn't exist, return false.
		if ( ! $this->isset_internal( $key, $group ) ) {
			$return = false;
		}

		// Delete cached item and return true.
		unset( $this->cache[ $group ][ $key ] );

		// Delete the cache file.
		if ( $this->focus_file_exists( $key, $group ) ) {
			unlink( $this->get_focus_file( $key, $group ) ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
		}

		// Invalidate expiration cache since we deleted the file.
		$this->invalidate_expiration_cache( $key, $group );

		// Stats.
		$this->group_ops[ $group ][] = 'Delete ' . $key;

		return $return;
	}

	/**
	 * Remove the contents of all cache keys in the group.
	 *
	 * @since 0.1.0
	 * @access public
	 *
	 * @param string|false $group Optional. Where the cache contents are grouped. Default false.
	 * @return bool False if not deleted and true on success.
	 */
	public function delete_group( string|false $group = false ): bool {
		if ( false === $group ) {
			return false;
		}

		if ( ! $this->should_persist( $group ) && ! isset( $this->cache[ $group ] ) ) {
			return false;
		}

		// Delete local cache group.
		unset( $this->cache[ $group ] );

		// Mark all files as expired, just in case delete times out.
		foreach ( glob( $this->cache_dir . $group . '/*.*' ) as $filename ) {
			if ( is_file( $filename ) ) {
				touch( $filename, time() - 3600 ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_touch
			}
		}

		// Delete the cache group dir.
		$this->rm_cache_dir( $this->cache_dir . $group );

		return true;
	}

	/**
	 * Clears the object cache of all data.
	 *
	 * @since 0.1.0
	 * @access public
	 *
	 * @return true Always returns true.
	 */
	public function flush(): bool {
		// Delete all data in cache directory, empty memory cache.
		$this->rm_cache_dir( $this->cache_dir );
		$this->cache = array();
		return true;
	}

	/**
	 * Flush the object cache's runtime cache.
	 *
	 * This method only clears the in-memory cache, not the persistent
	 * file-based cache.
	 *
	 * @since 0.2.0
	 * @access public
	 *
	 * @return true Always returns true.
	 */
	public function flush_runtime(): bool {
		$this->cache = array();
		return true;
	}

	/**
	 * Retrieves the cache contents, if it exists.
	 *
	 * The contents will be first attempted to be retrieved by searching by the
	 * key in the cache group. If the cache is hit (success) then the contents
	 * are returned.
	 *
	 * On failure, the number of cache misses will be incremented.
	 *
	 * @since 0.1.0
	 * @access public
	 *
	 * @param int|string $key What the contents in the cache are called.
	 * @param string     $group Where the cache contents are grouped.
	 * @param bool       $force Whether to force a refetch rather than relying on the local cache (default is false).
	 * @param bool       $found Optional. Whether the key was found in the cache. Disambiguates a return of false, a storable value. Passed by reference. Default null.
	 * @param bool       $stat  Optional. Whether or not to record stats.  Default true.
	 * @return bool|mixed False on failure to retrieve contents or the cache contents on success
	 */
	public function get( int|string $key, string $group = 'default', bool $force = false, ?bool &$found = null, bool $stat = true ): mixed {
		// Skip persistent cache operations during WordPress installation.
		if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
			( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
			$found = false;
			return false;
		}

		if ( ! $this->is_valid_key( $key ) ) {
			$found = false;
			return false;
		}

		$group = $this->sanitize_cache_group( $group );
		$key   = $this->key( $key, $group );

		// Memory cache exists, please grab.
		if ( $this->isset_internal( $key, $group ) && ! $force ) {
			// Check if the cached file has expired.
			if ( $this->focus_file_exists( $key, $group ) && $this->get_expiration( $key, $group ) < 0 ) {
				// File has expired, remove from memory cache and proceed to load fresh data.
				unset( $this->cache[ $group ][ $key ] );
			} else {
				// Stats.
				if ( $stat ) {
					$this->group_ops[ $group ][] = 'Hit (Mem): ' . $key;
					++$this->cache_hits;
				}

				$found = true;
				return $this->cache[ $group ][ $key ];
			}
		}

		// FOCUS Cache file exists, please grab.
		if ( $this->focus_file_exists( $key, $group ) ) {
			// If the object has expired, remove it from the cache and return false to force a refresh.
			if ( $this->get_expiration( $key, $group ) < 0 ) {
				$this->delete( $key, $group );

				// Stats.
				if ( $stat ) {
					$this->group_ops[ $group ][] = 'Miss (Expired): ' . $key;
					++$this->cache_misses;
				}

				$found = false;
				return false;
			}

			$file_contents = file_get_contents( $this->get_focus_file( $key, $group ) ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
			if ( false === $file_contents ) {
				$found = false;
				return false;
			}

			$serialized_data = substr( $file_contents, strlen( $this->cache_serial_header ), - strlen( $this->cache_serial_footer ) );
			if ( empty( $serialized_data ) ) {
				// Corrupted cache file, delete it.
				$this->delete( $key, $group );
				$found = false;
				return false;
			}

			$unserialized_data = maybe_unserialize( $serialized_data );
			if ( false === $unserialized_data && serialize( false ) !== $serialized_data ) { // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.serialize_serialize
				// Corrupted cache file, delete it.
				$this->delete( $key, $group );
				$found = false;
				return false;
			}

			$this->cache[ $group ][ $key ] = $unserialized_data;

			// Stats.
			if ( $stat ) {
				$this->group_ops[ $group ][] = 'Hit (FOCUS): ' . $key;
				++$this->cache_hits;
			}

			if ( is_object( $this->cache[ $group ][ $key ] ) ) {
				$found = true;
				return clone $this->cache[ $group ][ $key ];
			}

			$found = true;
			return $this->cache[ $group ][ $key ];
		}

		if ( $stat ) {
			$this->group_ops[ $group ][] = 'Miss (Empty): ' . $key;
			++$this->cache_misses;
		}
		$found = false;
		return false;
	}

	/**
	 * Increments numeric cache item's value.
	 *
	 * @since 0.1.0
	 * @access public
	 *
	 * @param int|string $key    The cache key to increment.
	 * @param int        $offset Optional. The amount by which to increment the item's value. Default 1.
	 * @param string     $group  Optional. The group the key is in. Default 'default'.
	 * @return false|int False on failure, the item's new value on success.
	 */
	public function incr( int|string $key, int $offset = 1, string $group = 'default' ): int|false {
		if ( ! $this->is_valid_key( $key ) ) {
			return false;
		}

		$group = $this->sanitize_cache_group( $group );
		$key   = $this->key( $key, $group );

		// Key/Group doesn't exist, return false.
		if ( ! $this->isset_internal( $key, $group ) ) {
			return false;
		}

		// Get current expiration BEFORE modifying the value to avoid race conditions.
		$current_expiry = $this->get_expiration( $key, $group );
		if ( $current_expiry < 0 ) {
			// Value has expired, delete it and return false.
			$this->delete( $key, $group );
			return false;
		}

		// Sanitize value.
		$this->cache[ $group ][ $key ] = (int) $this->cache[ $group ][ $key ];

		// Sanitize offset.
		$offset = (int) $offset;

		// Increment value.
		$this->cache[ $group ][ $key ] += $offset;

		// Never go below 0.
		if ( $this->cache[ $group ][ $key ] < 0 ) {
			$this->cache[ $group ][ $key ] = 0;
		}

		// Save new value to the cache with preserved expiration.
		$this->set( $key, $this->cache[ $group ][ $key ], $group, $current_expiry );

		// Return new value.
		return $this->cache[ $group ][ $key ];
	}

	/**
	 * Replaces the contents in the cache, if contents already exist.
	 *
	 * @since 0.1.0
	 * @access public
	 *
	 * @see WP_Object_Cache::set()
	 *
	 * @param int|string $key    What to call the contents in the cache.
	 * @param mixed      $data   The contents to store in the cache.
	 * @param string     $group  Optional. Where to group the cache contents. Default 'default'.
	 * @param int        $expire Optional. When to expire the cache contents. Default 0 (no expiration).
	 * @return bool False if not exists, true if contents were replaced.
	 */
	public function replace( int|string $key, mixed $data, string $group = 'default', int $expire = 0 ): bool {
		if ( ! $this->is_valid_key( $key ) ) {
			return false;
		}

		$group = $this->sanitize_cache_group( $group );
		$key   = $this->key( $key, $group );

		// Key/Group doesn't exist, return false.
		if ( ! $this->isset_internal( $key, $group ) ) {
			return false;
		}

		return $this->set( $key, $data, $group, (int) $expire );
	}

	/**
	 * Sets the data contents into the cache.
	 *
	 * The cache contents is grouped by the $group parameter followed by the
	 * $key. This allows for duplicate ids in unique groups. Therefore, naming of
	 * the group should be used with care and should follow normal function
	 * naming guidelines outside of core WordPress usage.
	 *
	 * The $expire parameter is not used, because the cache will automatically
	 * expire for each time a page is accessed and PHP finishes. The method is
	 * more for cache plugins which use files.
	 *
	 * @since 0.1.0
	 * @access public
	 *
	 * @param int|string $key    What to call the contents in the cache.
	 * @param mixed      $data   The contents to store in the cache.
	 * @param string     $group  Optional. Where to group the cache contents. Default 'default'.
	 * @param int        $expire Not Used.
	 * @return true Always returns true.
	 */
	public function set( int|string $key, mixed $data, string $group = 'default', int $expire = 0 ): bool {
		// Skip persistent cache operations during WordPress installation.
		if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
			( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
			return true;
		}

		if ( ! $this->is_valid_key( $key ) ) {
			return false;
		}

		$group = $this->sanitize_cache_group( $group );
		$key   = $this->key( $key, $group );

		if ( 0 === $expire ) {
			$expire = $this->default_expiration;
		}

		// Clone objects.
		if ( is_object( $data ) ) {
			$data = clone $data;
		}

		$this->cache[ $group ][ $key ] = $data;

		// Periodically check memory usage (every 100th set operation).
		static $set_counter = 0;
		++$set_counter;
		if ( 0 === $set_counter % 100 ) {
			$this->maybe_cleanup_memory();
		}

		// Stats.
		$this->group_ops[ $group ][] = 'Set ' . $group . '/' . $key . ' (' . $expire . 's)';

		return $this->save( $key, $data, $group, $expire );
	}

	/**
	 * Echoes the stats of the caching.
	 *
	 * Gives the cache hits, and cache misses. Also prints every cached group,
	 * key and the data.
	 *
	 * @since 0.1.0
	 * @access public
	 */
	public function stats(): void {
		?>
		<p><strong>Cache Hits:</strong> <?php echo esc_html( $this->cache_hits ); ?></p>
		<p><strong>Cache Misses:</strong> <?php echo esc_html( $this->cache_misses ); ?></p>
		<h3>Object Cache:</h3>
		<?php foreach ( $this->group_ops as $group => $ops ) : ?>
			<?php
			if ( ! isset( $_GET['debug_queries'] ) && 500 < count( $ops ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
				$ops = array_slice( $ops, 0, 500 );
				echo "<big>Too many to show! <a href='" . esc_url( add_query_arg( 'debug_queries', 'true' ) ) . "'>Show them anyway</a>.</big>\n";
			}
			?>
			<h4><?php echo esc_html( $group ); ?> commands</h4>
			<div style="font-family: monospace;">
				<?php
				$lines = array();
				foreach ( $ops as $op ) {
					echo wp_kses_post( $this->colorize_debug_line( $op ) . '<br/>' );
				}
				?>
			</div>
		<?php endforeach; ?>
		<?php
	}

	/**
	 * Adds multiple values to the cache in one call.
	 *
	 * @since 6.0.0
	 * @access public
	 *
	 * @param array  $data   Array of keys and values to be added.
	 * @param string $group  Optional. Where the cache contents are grouped. Default 'default'.
	 * @param int    $expire Optional. When to expire the cache contents, in seconds.
	 *                       Default 0 (no expiration).
	 * @return bool[] Array of return values, grouped by key. Each value is either
	 *                true on success, or false if cache key and group already exist.
	 */
	public function add_multiple( array $data, string $group = 'default', int $expire = 0 ): array {
		if ( empty( $data ) ) {
			return array();
		}

		$group         = $this->sanitize_cache_group( $group );
		$results       = array();
		$success_count = 0;

		// Ensure directory exists once (optimization).
		$this->ensure_cache_dir_exists( $group );

		// Process all keys in batch.
		foreach ( $data as $key => $value ) {
			if ( ! $this->is_valid_key( $key ) ) {
				$results[ $key ] = false;
				continue;
			}

			$cache_key = $this->key( $key, $group );

			// Check if key already exists (add only if it doesn't exist).
			if ( $this->isset_internal( $cache_key, $group ) ) {
				$results[ $key ] = false;
				continue;
			}

			// Update memory cache.
			$this->cache[ $group ][ $cache_key ] = $value;

			// Write to disk.
			if ( $this->save( $cache_key, $value, $group, $expire ) ) {
				$results[ $key ] = true;
				++$success_count;
			} else {
				$results[ $key ] = false;
				// Remove from memory if disk write failed.
				unset( $this->cache[ $group ][ $cache_key ] );
			}
		}

		// Single group stat entry for the batch operation.
		$this->group_ops[ $group ][] = sprintf( 'add_multiple (%d keys, %d successful)', count( $data ), $success_count );

		return $results;
	}

	/**
	 * Sets multiple values to the cache in one call.
	 *
	 * @since 6.0.0
	 * @access public
	 *
	 * @param array  $data   Array of keys and values to be set.
	 * @param string $group  Optional. Where the cache contents are grouped. Default 'default'.
	 * @param int    $expire Optional. When to expire the cache contents, in seconds.
	 *                       Default 0 (no expiration).
	 * @return bool[] Array of return values, grouped by key. Each value is either
	 *                true on success, or false on failure.
	 */
	public function set_multiple( array $data, string $group = 'default', int $expire = 0 ): array {
		if ( empty( $data ) ) {
			return array();
		}

		$group         = $this->sanitize_cache_group( $group );
		$results       = array();
		$success_count = 0;

		// Ensure directory exists once (optimization).
		$this->ensure_cache_dir_exists( $group );

		// Process all keys in batch.
		foreach ( $data as $key => $value ) {
			if ( ! $this->is_valid_key( $key ) ) {
				$results[ $key ] = false;
				continue;
			}

			$cache_key = $this->key( $key, $group );

			// Update memory cache.
			$this->cache[ $group ][ $cache_key ] = $value;

			// Write to disk.
			if ( $this->save( $cache_key, $value, $group, $expire ) ) {
				$results[ $key ] = true;
				++$success_count;
			} else {
				$results[ $key ] = false;
				// Remove from memory if disk write failed.
				unset( $this->cache[ $group ][ $cache_key ] );
			}
		}

		// Single group stat entry for the batch operation.
		$this->group_ops[ $group ][] = sprintf( 'set_multiple (%d keys, %d successful)', count( $data ), $success_count );

		return $results;
	}

	/**
	 * Retrieves multiple values from the cache in one call.
	 *
	 * @since 5.5.0
	 * @access public
	 *
	 * @param array  $keys  Array of keys under which the cache contents are stored.
	 * @param string $group Optional. Where the cache contents are grouped. Default 'default'.
	 * @param bool   $force Optional. Whether to force an update of the local cache
	 *                      from the persistent cache. Default false.
	 * @return array Array of return values, grouped by key. Each value is either
	 *               the cache contents on success, or false on failure.
	 */
	public function get_multiple( array $keys, string $group = 'default', bool $force = false ): array {
		if ( empty( $keys ) ) {
			return array();
		}

		$group        = $this->sanitize_cache_group( $group );
		$results      = array();
		$missing_keys = array();
		$cache_hits   = 0;
		$cache_misses = 0;

		// First pass: check memory cache for all keys (fast batch operation).
		foreach ( $keys as $key ) {
			if ( ! $this->is_valid_key( $key ) ) {
				$results[ $key ] = false;
				++$cache_misses;
				continue;
			}

			$cache_key = $this->key( $key, $group );

			// Check memory first (unless forced).
			if ( ! $force && $this->isset_internal( $cache_key, $group ) ) {
				$results[ $key ] = $this->cache[ $group ][ $cache_key ];
				++$cache_hits;
			} else {
				$missing_keys[ $key ] = $cache_key;
			}
		}

		// Second pass: load missing keys from disk in batch.
		if ( ! empty( $missing_keys ) ) {
			foreach ( $missing_keys as $key => $cache_key ) {
				$disk_value = $this->load_from_disk( $cache_key, $group );
				if ( false !== $disk_value ) {
					$results[ $key ] = $disk_value;
					// Update memory cache for future hits.
					$this->cache[ $group ][ $cache_key ] = $disk_value;
					++$cache_hits;
				} else {
					$results[ $key ] = false;
					++$cache_misses;
				}
			}
		}

		// Update global stats.
		$this->cache_hits   += $cache_hits;
		$this->cache_misses += $cache_misses;

		// Single group stat entry for the batch operation.
		$this->group_ops[ $group ][] = sprintf( 'get_multiple (%d keys, %d hits, %d misses)', count( $keys ), $cache_hits, $cache_misses );

		return $results;
	}

	/**
	 * Deletes multiple values from the cache in one call.
	 *
	 * @since 6.0.0
	 * @access public
	 *
	 * @param array  $keys  Array of keys under which the cache to deleted.
	 * @param string $group Optional. Where the cache contents are grouped. Default 'default'.
	 * @return bool[] Array of return values, grouped by key. Each value is either
	 *                true on success, or false if the contents were not deleted.
	 */
	public function delete_multiple( array $keys, string $group = 'default' ): array {
		if ( empty( $keys ) ) {
			return array();
		}

		$group           = $this->sanitize_cache_group( $group );
		$results         = array();
		$files_to_delete = array();
		$success_count   = 0;

		// First pass: process all keys and collect files to delete.
		foreach ( $keys as $key ) {
			if ( ! $this->is_valid_key( $key ) ) {
				$results[ $key ] = false;
				continue;
			}

			$cache_key = $this->key( $key, $group );

			// Check if key exists in memory or on disk.
			$existed_in_memory = $this->isset_internal( $cache_key, $group );
			$file_path         = $this->get_focus_file( $cache_key, $group );
			$exists_on_disk    = $this->focus_file_exists( $cache_key, $group );

			// Remove from memory cache.
			unset( $this->cache[ $group ][ $cache_key ] );

			// Determine success (existed in memory OR on disk).
			if ( $existed_in_memory || $exists_on_disk ) {
				$results[ $key ] = true;
				++$success_count;

				// Collect file for deletion if it exists.
				if ( $exists_on_disk ) {
					$files_to_delete[] = $file_path;
				}
			} else {
				$results[ $key ] = false;
			}
		}

		// Second pass: batch delete files from disk.
		foreach ( $files_to_delete as $file_path ) {
			unlink( $file_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
		}

		// Single group stat entry for the batch operation.
		$this->group_ops[ $group ][] = sprintf( 'delete_multiple (%d keys, %d successful)', count( $keys ), $success_count );

		return $results;
	}

	/**
	 * Removes all cache items in a group.
	 *
	 * @since 6.1.0
	 * @access public
	 *
	 * @param string $group Name of group to remove from cache.
	 * @return bool True if group was flushed, false otherwise.
	 */
	public function flush_group( string $group ): bool {
		return $this->delete_group( $group );
	}

	/**
	 * Switches the interal blog ID.
	 *
	 * This changes the blog ID used to create keys in blog specific groups.
	 *
	 * @since 0.1.0
	 * @access public
	 *
	 * @param int|false $blog_id Blog ID, or false to do nothing.
	 *
	 * @return void
	 */
	public function switch_to_blog( int|false $blog_id = false ): void {
		if ( false !== $blog_id && (int) $blog_id >= 1 && is_multisite() ) {
			$this->blog_prefix = 'Site ' . (int) $blog_id;
		}
	}

	/**
	 * Serves as a utility function to colorize cache stats.
	 *
	 * @since 0.1.0
	 * @access protected
	 *
	 * @param string $line Stats to be colorized.
	 * @return string HTML colorized stats.
	 */
	protected function colorize_debug_line( string $line ): string {
		$colors = array(
			'Get'    => 'green',
			'Set'    => 'purple',
			'Add'    => 'blue',
			'Delete' => 'red',
			'Hit'    => 'orange',
			'Miss'   => 'brown',
		);

		$cmd = substr( $line, 0, strpos( $line, ' ' ) );

		$cmd2 = '<span style="color:' . esc_attr( $colors[ $cmd ] ) . '">' . esc_html( $cmd ) . '</span>';

		return $cmd2 . substr( $line, strlen( $cmd ) );
	}

	/**
	 * Does this group use persistent storage?
	 *
	 * @since 0.1.0
	 *
	 * @param string $group Cache group.
	 * @return bool        true if the group is persistent, false if not.
	 */
	public function should_persist( string $group ): bool {
		return empty( $this->non_persistent_groups[ $group ] );
	}

	/**
	 * Check if we're in a WP-CLI context.
	 *
	 * @since 1.1.0
	 * @return bool True if WP-CLI context, false otherwise.
	 */
	public function is_wp_cli(): bool {
		if ( null === $this->is_wp_cli ) {
			$this->is_wp_cli = defined( 'WP_CLI' ) && WP_CLI;
		}
		return $this->is_wp_cli;
	}

	/**
	 * Check if we're in a CRON context.
	 *
	 * @since 1.1.0
	 * @return bool True if CRON context, false otherwise.
	 */
	public function is_doing_cron(): bool {
		if ( null === $this->is_doing_cron ) {
			$this->is_doing_cron = defined( 'DOING_CRON' ) && DOING_CRON;
		}
		return $this->is_doing_cron;
	}

	/**
	 * Check if we're in an XML-RPC context.
	 *
	 * @since 1.1.0
	 * @return bool True if XML-RPC context, false otherwise.
	 */
	public function is_xmlrpc_request(): bool {
		if ( null === $this->is_xmlrpc_request ) {
			$this->is_xmlrpc_request = defined( 'XMLRPC_REQUEST' ) && XMLRPC_REQUEST;
		}
		return $this->is_xmlrpc_request;
	}

	/**
	 * Serves as a utility function to determine whether a key exists in the cache.
	 *
	 * @since 0.1.0
	 * @access protected
	 *
	 * @param int|string $key   Cache key to check for existence.
	 * @param string     $group Cache group for the key existence check.
	 * @return bool Whether the key exists in the cache for the given group.
	 */
	protected function isset_internal( int|string $key, string $group ): bool {
		return isset( $this->cache[ $group ] ) && ( isset( $this->cache[ $group ][ $key ] ) || array_key_exists( $key, $this->cache[ $group ] ) );
	}

	/**
	 * Serves as a utility function to determine if a cache file exists.
	 *
	 * @since 0.1.0
	 * @access protected
	 *
	 * @param int|string $key   Cache key to check for existence.
	 * @param string     $group Cache group for the key existence check.
	 * @return bool Whether the cache file key exists.
	 */
	protected function focus_file_exists( int|string $key, string $group ): bool {
		return file_exists( $this->get_focus_file( $key, $group ) );
	}

	/**
	 * Serves as a utility function to determine the cache expiration.
	 *
	 * @since 0.1.0
	 * @access protected
	 *
	 * @param int|string $key   Cache key to check.
	 * @param string     $group Cache group for the key check.
	 * @return int Seconds until the cache expires.
	 */
	protected function get_expiration( int|string $key, string $group ): int {
		$cache_key    = $group . ':' . $key;
		$current_time = time();

		// Check if we have a cached expiration result from this request.
		if ( isset( $this->expiration_cache[ $cache_key ] ) ) {
			$cached_data = $this->expiration_cache[ $cache_key ];
			// Use cached result if it's from the same second (transaction-level caching).
			if ( $current_time === $cached_data['calculated_at'] ) {
				return ( $cached_data['mtime'] - $current_time );
			}
		}

		if ( $this->focus_file_exists( $key, $group ) ) {
			$file_path = $this->get_focus_file( $key, $group );
			$mtime     = filemtime( $file_path );

			// Cache the result for this transaction (same-second requests).
			$this->expiration_cache[ $cache_key ] = array(
				'mtime'         => $mtime,
				'calculated_at' => $current_time,
			);

			return ( $mtime - $current_time );
		}

		return 0;
	}

	/**
	 * Serves as a utility function to determine the cache file.
	 *
	 * @since 0.1.0
	 * @access protected
	 *
	 * @param int|string $key   Cache key to check.
	 * @param string     $group Cache group for the key check.
	 * @return string The cache file.
	 */
	protected function get_focus_file( int|string $key, string $group ): string {
		$cache_key = $group . ':' . $key;

		// Check if we already calculated this path.
		if ( isset( $this->file_path_cache[ $cache_key ] ) ) {
			return $this->file_path_cache[ $cache_key ];
		}

		// Some characters might cause problems with the file system.
		$protected_chars = array(
			'/'  => rawurlencode( '/' ),
			'\\' => rawurlencode( '\\' ),
			'?'  => rawurlencode( '?' ),
			'*'  => rawurlencode( '*' ),
			'|'  => rawurlencode( '|' ),
			'"'  => rawurlencode( '"' ),
			'\'' => rawurlencode( '\'' ),
			'<'  => rawurlencode( '<' ),
			'>'  => rawurlencode( '>' ),
			':'  => rawurlencode( ':' ),
		);

		$safe_key  = str_replace( array_keys( $protected_chars ), $protected_chars, $key );
		$file_path = $this->cache_dir . $group . '/' . $safe_key . '.php';

		// Cache the result for future use.
		$this->file_path_cache[ $cache_key ] = $file_path;

		// Cleanup file path cache if it gets too large.
		if ( count( $this->file_path_cache ) > $this->max_file_path_cache_items ) {
			$this->file_path_cache = array_slice( $this->file_path_cache, -$this->file_path_cache_cleanup_size, null, true );
		}

		return $file_path;
	}

	/**
	 * Normalizes key
	 *
	 * @since 0.1.0
	 * @access public
	 *
	 * @param int|string $key   Cache key to check.
	 * @param string     $group Cache group for the key check.
	 * @return string Normalized copy of key.
	 */
	public function key( int|string $key, string $group ): string {
		$group = $this->sanitize_cache_group( $group );

		$prefix = $this->key_salt;

		if ( ! empty( $this->global_groups[ $group ] ) ) {
			$prefix .= $this->global_prefix;
		} else {
			$prefix .= $this->blog_prefix;
		}

		if ( empty( $prefix ) ) {
			$prefix = 'WP';
		}

		// Remove whitespace.
		$prefix = preg_replace( '/\s+/', '', $prefix );
		$key    = preg_replace( '/\s+/', '', (string) $key );

		$normalized_key = $prefix . ':' . $key;

		// Remove dulicate prefixes.  Where are these coming from?!
		$normalized_key = preg_replace( '/^' . $prefix . ':' . $prefix . ':/', $prefix . ':', $normalized_key );

		return $normalized_key;
	}

	/**
	 * Salts cache key prefix
	 *
	 * @since 0.1.0
	 * @access protected
	 *
	 * @param string $key_salt Salt to use.
	 */
	protected function salt_keys( string $key_salt ): void {
		if ( strlen( $key_salt ) ) {
			$this->key_salt = $key_salt . ':';
		} else {
			$this->key_salt = '';
		}
	}

	/**
	 * Generates a normalized preload cache key based on domain, URL and query parameters.
	 * Used to uniquely identify cache preload files for specific pages across multiple domains.
	 *
	 * @since 1.1.0
	 * @access protected
	 *
	 * @return string|false Normalized preload cache key including domain and blog context, or false if preload is disabled.
	 */
	public function get_preload_key(): string|false {
		// Skip if preload is not enabled.
		if ( ! WP_FOCUS_CACHE_PRELOAD && ! ( isset( $this->test_preload_enabled ) && $this->test_preload_enabled ) ) {
			return false;
		}

		global $blog_id;

		// Skip preload for non-web contexts.
		if ( $this->is_wp_cli() ) {
			return false; // Disable preload for WP-CLI.
		}
		if ( $this->is_doing_cron() ) {
			return false; // Disable preload for cron jobs.
		}
		if ( $this->is_xmlrpc_request() ) {
			return false; // Disable preload for XML-RPC requests.
		}

		// Skip preload for non-GET requests.
		$request_method = isset( $_SERVER['REQUEST_METHOD'] ) ? $_SERVER['REQUEST_METHOD'] : 'GET'; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.MissingUnslash, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
		if ( 'GET' !== $request_method ) {
			return false; // Only preload GET requests.
		}

		// Get domain for multi-domain WordPress sites.
		$domain      = isset( $_SERVER['HTTP_HOST'] ) ? $_SERVER['HTTP_HOST'] : 'localhost'; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.MissingUnslash, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
		$domain_hash = md5( $domain );

		// Get current URL and normalize it.
		$url = '';
		if ( isset( $_SERVER['REQUEST_URI'] ) ) {
			$url = $_SERVER['REQUEST_URI']; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.MissingUnslash, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
		}

		// Remove trailing slash for consistency.
		$url = rtrim( $url, '/' );

		// Handle query parameters - sort them for consistency.
		$query_params = array();
		if ( isset( $_SERVER['QUERY_STRING'] ) && ! empty( $_SERVER['QUERY_STRING'] ) ) {
			parse_str( $_SERVER['QUERY_STRING'], $query_params ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.MissingUnslash, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
			ksort( $query_params );
		}

		// Build normalized URL with sorted query string.
		$normalized_url = $url;
		if ( ! empty( $query_params ) ) {
			$normalized_url .= '?' . http_build_query( $query_params );
		}

		// Create hash for the URL to avoid filesystem issues.
		$url_hash = md5( $normalized_url );

		// Include domain and blog ID for multisite and multi-domain support.
		$blog_id     = isset( $blog_id ) ? $blog_id : 1; // phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited
		$preload_key = $domain_hash . '_' . $url_hash . '_' . $blog_id;

		return $preload_key;
	}

	/**
	 * Loads cache preload data from disk if available and not expired.
	 * Implements two-level expiration validation for optimal performance.
	 *
	 * @since 1.1.0
	 * @access protected
	 */
	protected function load_preload_cache(): void {
		// Skip during WordPress installation.
		if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
			( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
			return;
		}

		$preload_key = $this->get_preload_key();
		// Skip if preload is disabled for this context.
		if ( false === $preload_key ) {
			return;
		}

		$preload_file = $this->preload_dir . $preload_key . '.php';

		// First level: Check if preload file exists and is not expired.
		if ( ! file_exists( $preload_file ) ) {
			return;
		}

		$preload_file_time = filemtime( $preload_file );
		if ( ! $preload_file_time || ( $preload_file_time + WP_FOCUS_PRELOAD_TTL ) <= time() ) {
			// Preload file is expired, clean it up and skip.
			unlink( $preload_file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
			return;
		}

		// Load and deserialize preload data.
		$preload_data = $this->load_preload_file( $preload_file );
		if ( ! $preload_data || ! isset( $preload_data['cache_data'] ) || ! isset( $preload_data['file_times'] ) ) {
			// Corrupted preload file, clean it up.
			unlink( $preload_file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
			return;
		}

		$current_time = time();

		// Second level: Validate individual cache items and restore non-expired ones.
		foreach ( $preload_data['cache_data'] as $group => $items ) {
			// Skip non-persistent groups. (they shouldn't be in preload anyway).
			if ( ! empty( $this->non_persistent_groups[ $group ] ) ) {
				continue;
			}

			foreach ( $items as $key => $value ) {
				// Check if we have file time data for this item.
				if ( ! isset( $preload_data['file_times'][ $group ][ $key ] ) ) {
					continue;
				}

				$item_filemtime = $preload_data['file_times'][ $group ][ $key ];

				// Check if item is expired using FOCUS cache logic (filemtime < current_time).
				if ( $item_filemtime < $current_time ) {
					continue; // Skip expired item.
				}

				// Item is valid, restore it to cache.
				if ( ! isset( $this->cache[ $group ] ) ) {
					$this->cache[ $group ] = array();
				}
				$this->cache[ $group ][ $key ] = $value;
			}
		}
	}

	/**
	 * Loads and deserializes a preload file from disk.
	 *
	 * @since 1.1.0
	 * @access protected
	 *
	 * @param string $preload_file Path to the preload file.
	 * @return array|false Preload data array or false on failure.
	 */
	protected function load_preload_file( string $preload_file ): array|false {
		$contents = file_get_contents( $preload_file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		if ( false === $contents ) {
			return false;
		}

		// Extract serialized data from the PHP file format.
		$data = substr( $contents, strlen( $this->cache_serial_header ), - strlen( $this->cache_serial_footer ) );
		if ( empty( $data ) ) {
			return false;
		}

		// Unserialize the data.
		$value = unserialize( $data ); // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.serialize_unserialize
		if ( false === $value && serialize( false ) !== $data ) { // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.serialize_serialize
			return false;
		}

		return $value;
	}

	/**
	 * Saves the current cache state to a preload file for future requests.
	 * Captures expiration metadata by checking individual cache file timestamps.
	 *
	 * @return void
	 */
	public function save_preload_cache(): void {
		// Skip if preload is not enabled.
		if ( ! WP_FOCUS_CACHE_PRELOAD && ! ( isset( $this->test_preload_enabled ) && $this->test_preload_enabled ) ) {
			return;
		}

		// Skip during WordPress installation or if cache is empty.
		if ( ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) ||
			( isset( $_SERVER['SCRIPT_NAME'] ) && strpos( $_SERVER['SCRIPT_NAME'], 'install.php' ) !== false ) || // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.MissingUnslash, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
			empty( $this->cache ) ) {
			return;
		}

		$preload_key = $this->get_preload_key();
		// Skip if preload is disabled for this context.
		if ( false === $preload_key ) {
			return;
		}

		$preload_file = $this->preload_dir . $preload_key . '.php';

		// If the preload file is less than 5 minutes old, skip saving.
		if ( file_exists( $preload_file ) && ( filemtime( $preload_file ) + WP_FOCUS_PRELOAD_TTL ) > time() ) {
			return; // Preload file is still fresh, no need to save again.
		}

		// Build cache data and file time metadata.
		$cache_data_to_save = array();
		$file_times         = array();

		foreach ( $this->cache as $group => $items ) {
			// Skip non-persistent groups.
			if ( ! empty( $this->non_persistent_groups[ $group ] ) ) {
				continue;
			}

			foreach ( $items as $key => $value ) {
				// Get the cache file for this item to check its file time.
				$cache_file = $this->get_focus_file( $key, $group );

				if ( file_exists( $cache_file ) ) {
					$cache_file_time = filemtime( $cache_file );

					// Only include items with valid file times.
					if ( false !== $cache_file_time ) {
						// Store cache data and file time.
						if ( ! isset( $cache_data_to_save[ $group ] ) ) {
							$cache_data_to_save[ $group ] = array();
							$file_times[ $group ]         = array();
						}

						$cache_data_to_save[ $group ][ $key ] = $value;
						$file_times[ $group ][ $key ]         = $cache_file_time;
					}
				}
			}
		}

		// Don't create empty preload files.
		if ( empty( $cache_data_to_save ) ) {
			return;
		}

		// Build simplified preload data structure.
		$preload_data = array(
			'cache_data' => $cache_data_to_save,
			'file_times' => $file_times,
		);

		// Save preload file using the same format as regular cache files.
		$this->save_preload_file( $preload_file, $preload_data );
	}

	/**
	 * Saves preload data to disk using the same format as regular cache files.
	 *
	 * @since 1.1.0
	 * @access protected
	 *
	 * @param string $preload_file Path to save the preload file.
	 * @param array  $preload_data The preload data to save.
	 * @return bool True on success, false on failure.
	 */
	protected function save_preload_file( string $preload_file, array $preload_data ): bool {
		// Ensure preload directory exists.
		if ( ! is_dir( $this->preload_dir ) ) {
			$this->mkdir( $this->preload_dir );
		}

		// Create temporary file.
		$temp_file = tempnam( $this->preload_dir, 'preload_tmp' );
		if ( false === $temp_file ) {
			return false;
		}

		// Serialize and add header/footer.
		$serial = $this->cache_serial_header . serialize( $preload_data ) . $this->cache_serial_footer; // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.serialize_serialize

		$fd = fopen( $temp_file, 'w' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fopen
		if ( false === $fd ) {
			unlink( $temp_file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
			return false;
		}

		$fwrite = fwrite( $fd, $serial ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fwrite
		fclose( $fd ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fclose

		if ( false === $fwrite ) {
			unlink( $temp_file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
			return false;
		}

		// Atomic move to final location.
		if ( ! rename( $temp_file, $preload_file ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.rename_rename
			unlink( $temp_file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
			return false;
		}

		return true;
	}

	/**
	 * Serves as a utility function to create cache group directories.
	 *
	 * @param string $group Cache group for directory creation.
	 *
	 * @return string The cache group directory.
	 */
	protected function make_group_dir( string $group = 'default' ): string {
		$cache_dir = $this->cache_dir;
		$make_dir  = '';

		foreach ( explode( '/', $group ) as $subdir ) {
			$make_dir .= $subdir . '/';
			$this->mkdir( $cache_dir . $make_dir );
		}

		return $cache_dir . $group . '/';
	}

	/**
	 * Serves as a utility function to create directories.
	 *
	 * @param string $dir Directory to create.
	 *
	 * @return bool True on success, false on failure.
	 */
	protected function mkdir( string $dir ): bool {
		// Give the new dirs the same perms as wp-content.
		$stat = stat( ABSPATH . 'wp-content' );
		if ( false === $stat ) {
			// Fallback permissions for test environment or when wp-content doesn't exist.
			$dir_perms  = 0755; // rwxr-xr-x.
			$file_perms = 0644; // rw-r--r--.
		} else {
			$dir_perms  = $stat['mode'] & 0007777; // Get the permission bits.
			$file_perms = $dir_perms & 0000666; // Remove execute bits for files.
		}

		// Make the base cache dir.
		if ( ! file_exists( $dir ) ) {
			if ( ! mkdir( $dir ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_mkdir
				return false;
			}
			chmod( $dir, $dir_perms ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_chmod
		}

		if ( ! file_exists( $dir . 'index.php' ) ) {
			touch( $dir . 'index.php' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_touch
			chmod( $dir . 'index.php', $file_perms ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_chmod
		}

		return is_dir( $dir ) && is_writable( $dir ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_is_writable
	}

	/**
	 * Serves as a utility function to delete directories.
	 *
	 * @param string $dir Directory to delete.
	 *
	 * @return bool True on success, false on failure.
	 */
	protected function rm_cache_dir( string $dir ): bool {
		$dir_object = @opendir( $dir ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged

		if ( false === $dir_object ) {
			return false;
		}

		$file_object = readdir( $dir_object );
		while ( false !== $file_object ) {
			if ( '.' === $file_object || '..' === $file_object ) {
				$file_object = readdir( $dir_object );
				continue;
			}

			$dir_path = $dir . DIRECTORY_SEPARATOR . $file_object;

			if ( is_dir( $dir_path ) ) {
				$this->rm_cache_dir( $dir_path );
			} else {
				unlink( $dir_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
			}
			$file_object = readdir( $dir_object );
		}

		closedir( $dir_object );
		rmdir( $dir ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_rmdir

		return true;
	}

	/**
	 * Serves as a utility function to create multisite cache group names.
	 *
	 * @param string $group Cache group to sanitize.
	 *
	 * @return string Sanitized cache group.
	 */
	public function sanitize_cache_group( string $group ): string {
		if ( empty( $group ) ) {
			$group = 'default';
		}
		return $group;
	}

	/**
	 * Determines whether a key is valid.
	 *
	 * @param int|string $key Cache key to validate.
	 *
	 * @return bool Whether the key is valid.
	 */
	protected function is_valid_key( int|string $key ): bool {
		if ( is_int( $key ) ) {
			return true;
		}

		if ( is_string( $key ) && '' !== trim( $key ) ) {
			return true;
		}

		$type = gettype( $key );

		if ( ! function_exists( '__' ) ) {
			wp_load_translations_early();
		}

		/* translators: %s: The type of the given cache key. */
		$message = sprintf( __( 'Cache key must be integer or non-empty string, %s given.', 'focus-cache' ), $type );
		_doing_it_wrong( esc_html( sprintf( '%s::%s', __CLASS__, debug_backtrace( DEBUG_BACKTRACE_IGNORE_ARGS, 2 )[1]['function'] ) ), esc_html( $message ), '6.1.0' ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_debug_backtrace

		return false;
	}


	/**
	 * Serves as a utility function to save the cache data to a file.
	 *
	 * @param int|string $key    What to call the contents in the cache.
	 * @param mixed      $data   The contents to store in the cache.
	 * @param string     $group  Optional. Where to group the cache contents. Default 'default'.
	 * @param int        $expire Cache expiration.
	 *
	 * @return bool True on success, false on failure.
	 */
	protected function save( int|string $key, mixed $data, string $group = 'default', int $expire = 0 ): bool {
		// Skip file operations for non-persistent groups.
		if ( ! $this->should_persist( $group ) ) {
			return true;
		}

		// Check available disk space (fail if less than 10MB available).
		$cache_dir  = $this->cache_dir;
		$free_bytes = disk_free_space( $cache_dir );
		if ( false !== $free_bytes && $free_bytes < $this->min_disk_space ) {
			// Log the issue but don't fail completely - just don't persist to disk.
			error_log( 'FOCUS Cache: Low disk space warning. Available: ' . round( $free_bytes / 1048576, 1 ) . 'MB' ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
			return false;
		}

		if ( 0 === $expire ) {
			$expire = $this->default_expiration;
		}

		// Give the new dirs the same perms as wp-content.
		$stat = stat( ABSPATH . 'wp-content' );
		if ( false === $stat ) {
			// Fallback permissions for test environment or when wp-content doesn't exist.
			$dir_perms  = 0755; // rwxr-xr-x.
			$file_perms = 0644; // rw-r--r--.
		} else {
			$dir_perms  = $stat['mode'] & 0007777; // Get the permission bits.
			$file_perms = $dir_perms & 0000666; // Remove execute bits for files.
		}

		// Make FOCUS Cache directories and temp file.
		$this->mkdir( $cache_dir );
		$group_dir  = $this->make_group_dir( $group );
		$cache_file = $this->get_focus_file( $key, $group );
		$temp_file  = tempnam( $cache_dir, 'tmp' );
		if ( false === $temp_file ) {
			return false;
		}

		// Serialize and add Header/Footer.
		// `maybe_serialize()` causes issues with variable typing, can't use.
		$serial = $this->cache_serial_header . serialize( $data ) . $this->cache_serial_footer; // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.serialize_serialize

		$fd = fopen( $temp_file, 'w' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fopen
		if ( false === $fd ) {
			return false;
		}

		$fwrite = fwrite( $fd, $serial ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fwrite
		if ( false === $fwrite ) {
			return false;
		}

		fclose( $fd ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fclose

		if ( ! rename( $temp_file, $cache_file ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.rename_rename
			unlink( $temp_file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
			return false;
		}

		$chmod = chmod( $cache_file, $file_perms ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_chmod
		if ( false === $chmod ) {
			return false;
		}

		// Set expiry.
		$touch = touch( $cache_file, time() + $expire ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_touch
		if ( false === $touch ) {
			return false;
		}

		// Invalidate expiration cache since we just wrote a new file with new expiration.
		$this->invalidate_expiration_cache( $key, $group );

		return true;
	}

	/**
	 * Ensures that a cache directory exists for the given group.
	 * This is an optimization for batch operations to avoid repeated directory creation.
	 *
	 * @param string $group The cache group.
	 *
	 * @return bool True if directory exists or was created, false on failure.
	 */
	protected function ensure_cache_dir_exists( string $group ): bool {
		$cache_dir = $this->cache_dir . DIRECTORY_SEPARATOR . $group;

		if ( is_dir( $cache_dir ) ) {
			return true;
		}

		$this->make_group_dir( $group );
		return is_dir( $cache_dir );
	}

	/**
	 * Loads a cache value directly from disk without checking memory cache.
	 * This is used for batch operations to avoid memory cache pollution.
	 *
	 * @param string $key   The cache key.
	 * @param string $group The cache group.
	 *
	 * @return mixed The cached value on success, false on failure.
	 */
	protected function load_from_disk( string $key, string $group ): mixed {
		// Check if file exists and hasn't expired.
		if ( ! $this->focus_file_exists( $key, $group ) ) {
			return false;
		}

		$cache_file = $this->get_focus_file( $key, $group );

		// Check expiration (negative value means expired).
		if ( $this->get_expiration( $key, $group ) < 0 ) {
			// File has expired, delete it.
			unlink( $cache_file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
			return false;
		}

		// Load and decode the data.
		$contents = file_get_contents( $cache_file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		if ( false === $contents ) {
			return false;
		}

		// Extract serialized data from the PHP file format..
		$data = substr( $contents, strlen( $this->cache_serial_header ), - strlen( $this->cache_serial_footer ) );
		if ( empty( $data ) ) {
			return false;
		}

		// Unserialize the data..
		$value = unserialize( $data ); // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.serialize_unserialize
		if ( false === $value && serialize( false ) !== $data ) { // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.serialize_serialize
			return false;
		}

		return $value;
	}

	/**
	 * Invalidates cached expiration data for a specific key.
	 * Called when we write to a file to ensure expiration cache stays fresh.
	 *
	 * @param string $key   The cache key.
	 * @param string $group The cache group.
	 *
	 * @return void
	 */
	protected function invalidate_expiration_cache( string $key, string $group ): void {
		$cache_key = $group . ':' . $key;
		unset( $this->expiration_cache[ $cache_key ] );
	}

	/**
	 * Checks FOCUS-specific cache memory usage and performs cleanup if necessary.
	 * Only manages FOCUS internal caches, not WordPress core's cache.
	 *
	 * @return void
	 */
	protected function maybe_cleanup_memory(): void {
		// Only cleanup FOCUS-specific auxiliary caches.
		// WordPress core manages $this->cache memory itself.

		// Cleanup file path cache if it gets too large..
		if ( count( $this->file_path_cache ) > $this->max_file_path_cache_items ) {
			$this->file_path_cache = array_slice( $this->file_path_cache, -$this->file_path_cache_cleanup_size, null, true );
		}

		// Cleanup expiration cache if it gets too large.
		if ( count( $this->expiration_cache ) > $this->max_expiration_cache_items ) {
			$this->expiration_cache = array_slice( $this->expiration_cache, -$this->expiration_cache_cleanup_size, null, true );
		}

		// Group operations are preserved for debugging.
	}
}
